// want package:"isgogo"
// Code generated by protoc-gen-gogo. DO NOT EDIT.
package gogo

type Msg struct {
	XXX_sizecache int32
}

func X() Msg {
	return Msg{}
}

func Y(Msg) {}

func Z() {
	var m Msg
	_ = m
}
